### ISSUE TITLE
Escape spaces in Bundler and Rails root pathnames

### ISSUE THREAD

**Issue by bradencanderson** [browserify-rails/browserify-rails#74]
`rake test` fails when Bundler.root has a space in the pathname, because spaces aren't properly escaped. `rails_path()` in `browserify_processor.rb` should also return an escaped path string.

To reproduce, just clone this repo into a folder with a space in the name and watch `rake test` fail all its test cases.

I'm having some success using Shellwords to escape path names, but I'm new to Ruby/Rails and still am getting 13 failures with escaped strings.

**Comment by yz0075** [comment]
:+1:  Please fix!

**Comment by mikelkew** [comment]
+1 Also having issues with this. Not just in testing, but also in normal usage.

**Comment by cymen** [comment]
Would you be able to try 0.9.3? It includes a PR to allow parentheses in the path and I think how it was done should fix your issues too.

**Comment by bradencanderson** [comment]
Nope it's still broken, but earlier in the tests now. The top-level rakefile runs `sh "cd #{dummy_dir} && npm install"`, which fails when dummy_dir has spaces.

**Comment by cymen** [comment]
@bradencanderson Thanks for checking. For some reason, I was confused on how to test this but realized it was easy. I'm in the middle of getting the gem compatible with current sass-rails and then I'll fix this issue.

**Comment by cymen** [comment]
I tried to fix this but it is complicated. Mostly because we have to generate commands to run on the command line when we shell out to run browserify. The spaces in the paths are causing a lot of issues. I could get the ones inside of Ruby fixed but there are still glitches when we get to NodeJS.

If anyone else wants to try, do this:

1) make a directory such as "a space"
2) "cd a\ space" and git clone this repo
3) run the tests -- note how some files get created at the same level as "a space" like "a\ space" and "a"

Now you can try using variations of Shellwords.shellescape, inspect, etc to try to get things tweaked to the right escaped string.

At some point, you'll end up with just that odd file named "a" being created and it'll be the browserify-incremental cache file. So now you're in NodeJS land and will have to figure out how craft a command line with a space in a path that works with browserify-incremental. Then go backwards and fix it in the Ruby file `lib/browserify-rails/browserify_processor.rb`.

I'm out of time on this for now.

**Comment by cymen** [comment]
@bradencanderson Can you confirm 1.0.0 fixes this bug? I believe it is now fixed. Thanks!

**Comment by bradencanderson** [comment]
Looks good, as far as I can tell. There is still one test failure:

```
1) Failure:
BrowserifyTest#test_uses_config/browserify.yml_to_mark_a_module_as_globally_available_via_--require [/Users/bca/dev/browserify-rails/test/compilation_test.rb:184]:
--- expected
+++ actual
@@ -5,7 +5,7 @@
   console.log('library', library);
 };

-},{\"./a_huge_library\":\"/Users/bca/dev/browserify-rails/test/dummy/app/assets/javascripts/a_huge_library.js\"}],\"/Users/bca/dev/browserify-rails/test/dummy/app/assets/javascripts/a_huge_library.js\":[function(require,module,exports){
+},{\"./a_huge_library\":\"/Users/bca/dev/browserify-rails/test/dummy/app/assets/javascripts/a_huge_library.js\"}],\"a_huge_library\":[function(require,module,exports){
 // pretend this file is 1 MB
 //
 // app_main.js is going to require() it and browserify.yml is going to tell it to use --require on it


25 runs, 45 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
```

I doubt it's related, because that test also fails in my control. Thanks!

**Comment by cymen** [comment]
@bradencanderson Are you using node 0.10 or 0.12 (I'm checking with `node --version`)? I have the problem that this test fails on Travis CI but not on my local. I'm using 0.12 locally and it's not failing.

**Comment by cymen** [comment]
I'm not sure what to do if it is the node version. I guess we could have the test check the node version and use one fixture for 0.10 and another 0.12. That would work and make CI happy again. Hrm...

**Comment by bradencanderson** [comment]
Was running 0.10, but I just updated to 0.12 and it's still failing.
